export const carriers = [
  {
    billingEmail: null,
    name: '2173995 ONTARIO INC',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'ROLLINGFREIGHT@OUTLOOK.COM',
    contactFax: null,
    contactName: 'GURPARTAP SINGH SANDHU',
    contactPhone: '647-548-6601',
    contactPhoneExt: null,
    dotNumber: '3048437',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 247552,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC048542',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: '3 HORN NEWBORN TRUCKING LLC',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'QNEWBORN@MSN.COM',
    contactFax: null,
    contactName: 'QUITEN NEWBORN',
    contactPhone: '404-721-7293',
    contactPhoneExt: null,
    dotNumber: '3499709',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 251583,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1154682',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'AAA Cooper / MME',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'swallace@aaacooper.com',
    contactFax: null,
    contactName: 'Steve Wallace',
    contactPhone: '334-671-3103',
    contactPhoneExt: null,
    dotNumber: '92261',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 1101,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-55889',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'aact',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ABF Freight',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'api@arcb.com',
    contactFax: null,
    contactName: null,
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '82866',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 11,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-29910',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['vltl', 'ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['vltl', 'ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'abfs',
    shipmentTerms: ['third_party'],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'A. Duie Pyle',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'ITSD@aduiepyle.com',
    contactFax: null,
    contactName: 'PYLE Support',
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '113594',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 12,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-39140',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: '',
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'pyle',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ADVANCE CARGO INC',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: 'ADVANCECARGOINC@GMAIL.COM',
    contactFax: null,
    contactName: 'ILLIA KONNOV',
    contactPhone: '307-776-7908',
    contactPhoneExt: null,
    dotNumber: '3995150',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 247734,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1499917',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'NOTONFILE',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ADVANCE ENERGY TECHNOLOGIES',
    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,
    contactEmail: null,
    contactFax: null,
    contactName: 'TIM CARLO',
    contactPhone: '518-371-2140',
    contactPhoneExt: null,
    dotNumber: '450061',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 246134,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: null,
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'NOTONFILE',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'A&J LOGISTICS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'ASHLEYHALLORAN1@GMAIL.COM',
    contactFax: null,
    contactName: 'ASHLEY EUGENE HALLORAN',
    contactPhone: '844-826-3519',
    contactPhoneExt: null,
    dotNumber: '3111281',
    factoringCompany: {
      address1: 'P.O Box 11407',
      address2: 'Ddept#2659',
      address_display: 'P.O Box 11407, Ddept#2659',
      address_name: 'Provident Commercial Finance LLC',
      assignment_notice: null,
      city: 'Birmingham',
      city_state_zip_display: 'Birmingham, AL, 35246, US',
      contactName: null,
      country_code: 'US',
      country_info: {
        country_code: 'US',
        country_name: 'United States',
        dial_code: '1',
        display: 'US - United States',
        friendly_name: 'Country',
        hash: '0756d653-7f93-45f7-8542-1d86e9b8656b',
        tmsCarrierId: 234,
      },
      create_date: '2023-09-13T20:32:18Z',
      created_by: 'Jacob Johnson',
      created_by_id: 248119,
      created_by_name: 'Jacob Johnson',
      created_for_id: null,
      created_for_name: null,
      email: 'talley@providentcfllc.com',
      fax: null,
      faxCountryCode: null,
      fax_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      friendly_name: 'Provident Commercial Finance LLC (Birmingham, AL)',
      hash: 'd6286bfc-4560-4c53-8896-47681493171e',
      tmsCarrierId: 6637,
      isActive: true,
      is_usa_can: true,
      last_updated_by: 'Jacob Johnson',
      last_updated_by_name: 'Jacob Johnson',
      last_updated_date: '2023-09-13T20:32:18Z',
      last_updated_for_name: null,
      name: 'Provident Commercial Finance LLC',
      notes: null,
      phone: null,
      phoneCountryCode: null,
      phone_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      phone_ext: null,
      postal_code: '35246',
      state_province: 'AL',
      tin: null,
    },
    faxCountryCode: null,
    tmsCarrierId: 247904,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC082840',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ALLAN TRUCKING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'Dispatch@allantrucking.com',
    contactFax: null,
    contactName: 'ALLAN FRIESEN',
    contactPhone: '260-350-3175',
    contactPhoneExt: null,
    dotNumber: '2423735',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 248927,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC834961',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ALYASCO XPRESS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'M.ISSA1958@YAHOO.COM',
    contactFax: null,
    contactName: 'MIKE ISSA',
    contactPhone: '708-715-7333',
    contactPhoneExt: null,
    dotNumber: '3729509',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 248320,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1315951',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'UNQUALIFIEDCARRIER',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'AMERICAN SPECIALIZED LOGISTICS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'JAYMIAMIASL@GMAIL.COM',
    contactFax: null,
    contactName: 'JEROMY TRASORRAS',
    contactPhone: '305-900-8770',
    contactPhoneExt: null,
    dotNumber: '3588653',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 251372,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1232753',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'AMG LOGISTICS INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'ARUs@AMGLOGISTICSINC.COM',
    contactFax: null,
    contactName: 'ARUSYAK HOVAKIMYAN',
    contactPhone: '310-598-3493',
    contactPhoneExt: null,
    dotNumber: '2544114',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252534,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC885475',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'A & N FISHBACK ACRES INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'NATHAN@FISHBACKACRES.COM',
    contactFax: null,
    contactName: 'NATHAN FISHBACK',
    contactPhone: '319-461-0825',
    contactPhoneExt: null,
    dotNumber: '3927279',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 248069,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1454483',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'NOTONFILE',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'A WORLD ABOVE TRUCKING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'AWORLDABOVETRUCKING@GMAIL.COM',
    contactFax: null,
    contactName: 'CHRISTOPHER WILLIAMS',
    contactPhone: '817-771-8427',
    contactPhoneExt: null,
    dotNumber: '4057243',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249649,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1538734',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'BAHAY VENTURES LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'BAHAY.VENTURESLLC@OUTLOOK.COM',
    contactFax: null,
    contactName: 'ROMMEL OBLIGACION',
    contactPhone: '731-501-6587',
    contactPhoneExt: null,
    dotNumber: '4090941',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249499,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1558418',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'B AND D TRANSPORTATION LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'banddtransportllc@gmail.com',
    contactFax: null,
    contactName: 'BRAD POWERS',
    contactPhone: '231-510-3162',
    contactPhoneExt: null,
    dotNumber: '2023950',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 248300,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC711707',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'B B TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: null,
    contactFax: null,
    contactName: 'JAMES M. MARTIN',
    contactPhone: '717-484-0681',
    contactPhoneExt: null,
    dotNumber: '1614876',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252138,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC596976',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'BILL BULLOCK',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'bullockagsvc@yahoo.com',
    contactFax: null,
    contactName: 'BILL BULLOCK',
    contactPhone: '563-213-0118',
    contactPhoneExt: null,
    dotNumber: '892362',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 246910,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC313248',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'BLADE RUNNER TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'bladetrucks@gmail.com',
    contactFax: null,
    contactName: 'TODD CLEASBY',
    contactPhone: '715-287-3290',
    contactPhoneExt: null,
    dotNumber: '2281507',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 250167,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC782432',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'BNT TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'TRANSPORTBNT@GMAIL.COM',
    contactFax: null,
    contactName: 'CARLO IFRIM',
    contactPhone: '216-224-2237',
    contactPhoneExt: null,
    dotNumber: '2329222',
    factoringCompany: {
      address1: 'PO Box 840267',
      address2: null,
      address_display: 'PO Box 840267',
      address_name: 'RTS FINANCIAL  SERVICE, INC',
      assignment_notice: null,
      city: 'Dallas',
      city_state_zip_display: 'Dallas, TX, 75284, US',
      contactName: null,
      country_code: 'US',
      country_info: {
        country_code: 'US',
        country_name: 'United States',
        dial_code: '1',
        display: 'US - United States',
        friendly_name: 'Country',
        hash: '0756d653-7f93-45f7-8542-1d86e9b8656b',
        tmsCarrierId: 234,
      },
      create_date: '2023-09-27T11:31:06Z',
      created_by: 'Jacob Johnson',
      created_by_id: 248119,
      created_by_name: 'Jacob Johnson',
      created_for_id: null,
      created_for_name: null,
      email: null,
      fax: null,
      faxCountryCode: null,
      fax_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      friendly_name: 'RTS FINANCIAL  SERVICE, INC (Dallas, TX)',
      hash: '4c454108-0c68-4c8e-99d3-bdc5679e4447',
      tmsCarrierId: 6686,
      isActive: true,
      is_usa_can: true,
      last_updated_by: 'Jacob Johnson',
      last_updated_by_name: 'Jacob Johnson',
      last_updated_date: '2023-09-27T11:31:06Z',
      last_updated_for_name: null,
      name: 'RTS FINANCIAL  SERVICE, INC',
      notes: 'rtsteam32-sm@rtsfinancial.com',
      phone: '(800) 860-7926',
      phoneCountryCode: null,
      phone_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      phone_ext: null,
      postal_code: '75284',
      state_province: 'TX',
      tin: null,
    },
    faxCountryCode: null,
    tmsCarrierId: 250817,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC795153',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CALHOUN DISTRIBUTION, INC.',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'INFO@CALHOUNDIST.COM',
    contactFax: null,
    contactName: 'JOSEPH A DZURENDA JR',
    contactPhone: '412-777-1616',
    contactPhoneExt: null,
    dotNumber: '443021',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 245702,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC241824',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CDS TRANSPORTS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'SPIVEYCDS@GMAIL.COM',
    contactFax: null,
    contactName: 'CEDRIC D SPIVEY',
    contactPhone: '804-530-1823',
    contactPhoneExt: null,
    dotNumber: '2427789',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 246834,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC836664',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CHRISTOPHER M WADDLE',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'CHRIS@ADMIRALTOYSTORAGE.COM',
    contactFax: null,
    contactName: 'CHRISTOPHER WADDLE',
    contactPhone: '775-440-6130',
    contactPhoneExt: null,
    dotNumber: '3417189',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252385,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1103610',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CHRISTOPHER M WADDLE',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'CHRIS@ADMIRALTOYSTORAGE.COM',
    contactFax: null,
    contactName: 'CHRISTOPHER WADDLE',
    contactPhone: '775-440-6130',
    contactPhoneExt: null,
    dotNumber: '3417189',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252379,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1103610',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CLARK TRANSFER, INC.',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'mreiprich@clarktransfer.com',
    contactFax: null,
    contactName: 'NORMA DEULL PRESIDENT',
    contactPhone: '717-238-6581',
    contactPhoneExt: null,
    dotNumber: '31782',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 251886,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC116859',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CLASS GLOBAL LOGISTICS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'CLASSGLOBALLOGISTICS@GMAIL.COM',
    contactFax: null,
    contactName: 'ALEJANDRO ALMAGUER',
    contactPhone: '305-987-1768',
    contactPhoneExt: null,
    dotNumber: '2834814',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249600,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC948281',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'C. M. W. TRANSPORT CO., INC.',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'tracy@cmwtransport.com',
    contactFax: null,
    contactName: 'DWIGHT MILLER',
    contactPhone: '260-347-1664',
    contactPhoneExt: null,
    dotNumber: '52285',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 251852,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC168113',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'COVENANT TRANSPORT',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'SAUTHIENTHUX789@GMAIL.COM',
    contactFax: null,
    contactName: 'URBANO VASQUEZ',
    contactPhone: '404-850-5119',
    contactPhoneExt: null,
    dotNumber: '4106798',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252029,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1567778',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'CPG LOGISTICS INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'CPGLOGISTICSINC@GMAIL.COM',
    contactFax: null,
    contactName: 'CORINA POPA',
    contactPhone: '630-433-6916',
    contactPhoneExt: null,
    dotNumber: '3782269',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252099,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1354413',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'Cross Country',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'cgeiger@shipcc.com',
    contactFax: null,
    contactName: null,
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '313378',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 154575,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-209657',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'ccyq',
    shipmentTerms: [],
    tenderEmail: 'None',
  },
  {
    billingEmail: null,
    name: 'D4W LOGISTICS LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'FRED.GUERRA@LIVE.COM',
    contactFax: null,
    contactName: 'FRED RICHARD GUERRA III',
    contactPhone: '833-256-1728',
    contactPhoneExt: null,
    dotNumber: '4109757',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 250806,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1569471',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'DAKOTA FREIGHT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'adam@dakotafreightllc.com',
    contactFax: null,
    contactName: 'ADAM WRIGHT',
    contactPhone: '701-550-1855',
    contactPhoneExt: null,
    dotNumber: '3729460',
    factoringCompany: {
      address1: 'P.O. Box 1000',
      address2: 'Dept. #848',
      address_display: 'P.O. Box 1000, Dept. #848',
      address_name: 'iThrive Funding',
      assignment_notice: null,
      city: 'MPHS',
      city_state_zip_display: 'MPHS, TN, 38148, US',
      contactName: null,
      country_code: 'US',
      country_info: {
        country_code: 'US',
        country_name: 'United States',
        dial_code: '1',
        display: 'US - United States',
        friendly_name: 'Country',
        hash: '0756d653-7f93-45f7-8542-1d86e9b8656b',
        tmsCarrierId: 234,
      },
      create_date: '2023-09-22T15:18:02Z',
      created_by: 'Jacob Johnson',
      created_by_id: 248119,
      created_by_name: 'Jacob Johnson',
      created_for_id: null,
      created_for_name: null,
      email: 'noa_ithrive@ithrivefunding.com',
      fax: null,
      faxCountryCode: null,
      fax_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      friendly_name: 'iThrive Funding (MPHS, TN)',
      hash: 'eb85cec0-d78c-413e-9e19-58aeee997c0b',
      tmsCarrierId: 6666,
      isActive: true,
      is_usa_can: true,
      last_updated_by: 'Jacob Johnson',
      last_updated_by_name: 'Jacob Johnson',
      last_updated_date: '2023-09-22T15:18:02Z',
      last_updated_for_name: null,
      name: 'iThrive Funding',
      notes: null,
      phone: null,
      phoneCountryCode: null,
      phone_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      phone_ext: null,
      postal_code: '38148',
      state_province: 'TN',
      tin: null,
    },
    faxCountryCode: null,
    tmsCarrierId: 248322,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1315915',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'DA RAN, INC.',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'JOHN@DARANINC.COM',
    contactFax: null,
    contactName: 'RANDY HANSON',
    contactPhone: '763-856-4000',
    contactPhoneExt: null,
    dotNumber: '310502',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252506,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC202808',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'DELLS CONTRACTING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'DELLSNEM@GMAIL.COM',
    contactFax: null,
    contactName: 'ANTHONY DELLACQUA',
    contactPhone: '240-532-9104',
    contactPhoneExt: null,
    dotNumber: '4096892',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 246002,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1562015',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'D&H RELIABLE TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'JONDOMINY@AOL.COM',
    contactFax: null,
    contactName: 'JON D. DOMINY',
    contactPhone: '727-401-0532',
    contactPhoneExt: null,
    dotNumber: '3726648',
    factoringCompany: {
      address1: 'P.O Box 1415',
      address2: null,
      address_display: 'P.O Box 1415',
      address_name: 'Phoenix Capital Group',
      assignment_notice: null,
      city: 'Des Moines',
      city_state_zip_display: 'Des Moines, IA, 50305, US',
      contactName: null,
      country_code: 'US',
      country_info: {
        country_code: 'US',
        country_name: 'United States',
        dial_code: '1',
        display: 'US - United States',
        friendly_name: 'Country',
        hash: '0756d653-7f93-45f7-8542-1d86e9b8656b',
        tmsCarrierId: 234,
      },
      create_date: '2023-10-11T13:45:12Z',
      created_by: 'Jacob Johnson',
      created_by_id: 248119,
      created_by_name: 'Jacob Johnson',
      created_for_id: null,
      created_for_name: null,
      email: null,
      fax: '623-298-3450',
      faxCountryCode: null,
      fax_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      friendly_name: 'Phoenix Capital Group (Des Moines, IA)',
      hash: 'd6c06ffd-58a1-4ca2-9907-40d5a66b1c69',
      tmsCarrierId: 6753,
      isActive: true,
      is_usa_can: true,
      last_updated_by: 'Jacob Johnson',
      last_updated_by_name: 'Jacob Johnson',
      last_updated_date: '2023-10-11T13:45:12Z',
      last_updated_for_name: null,
      name: 'Phoenix Capital Group',
      notes: null,
      phone: '623-298-3450',
      phoneCountryCode: null,
      phone_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      phone_ext: null,
      postal_code: '50305',
      state_province: 'IA',
      tin: null,
    },
    faxCountryCode: null,
    tmsCarrierId: 250298,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1313880',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'Diamond Line Delivery',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'support@smsdatacenter.com',
    contactFax: null,
    contactName: null,
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '887550',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 168469,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-386888',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'dlds',
    shipmentTerms: ['third_party'],
    tenderEmail: 'None',
  },
  {
    billingEmail: null,
    name: 'D L CARTER TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'dlcarterlogistics@gmail.com',
    contactFax: null,
    contactName: 'NARINE STANGL',
    contactPhone: '415-523-5212',
    contactPhoneExt: null,
    dotNumber: '3148733',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249310,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC103624',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'DMAR TRUCKING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'DMARTRUCKINGLLC@SSSNET.COM',
    contactFax: null,
    contactName: 'DANA M MARTY',
    contactPhone: '330-435-3005',
    contactPhoneExt: null,
    dotNumber: '1812768',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 252605,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC658501',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'DO NEXT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'DONEXTLLC@GMAIL.COM',
    contactFax: null,
    contactName: 'JUSTINA REKSTYS',
    contactPhone: '708-608-1025',
    contactPhoneExt: null,
    dotNumber: '3752547',
    factoringCompany: {
      address1: 'P.O. Box 961029',
      address2: null,
      address_display: 'P.O. Box 961029',
      address_name: 'Apex Capital Corp',
      assignment_notice: null,
      city: 'Fort Worth',
      city_state_zip_display: 'Fort Worth, TX, 76161, US',
      contactName: null,
      country_code: 'US',
      country_info: {
        country_code: 'US',
        country_name: 'United States',
        dial_code: '1',
        display: 'US - United States',
        friendly_name: 'Country',
        hash: '0756d653-7f93-45f7-8542-1d86e9b8656b',
        tmsCarrierId: 234,
      },
      create_date: '2023-08-31T18:32:14Z',
      created_by: 'Jacob Johnson',
      created_by_id: 248119,
      created_by_name: 'Jacob Johnson',
      created_for_id: null,
      created_for_name: null,
      email: 'billing@apexcapitalcorp.com',
      fax: '(800) 511-6022',
      faxCountryCode: null,
      fax_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      friendly_name: 'Apex Capital Corp (Fort Worth, TX)',
      hash: '7a8845e5-b42a-4ea8-9cfe-4304dc619f11',
      tmsCarrierId: 6604,
      isActive: true,
      is_usa_can: true,
      last_updated_by: 'Jacob Johnson',
      last_updated_by_name: 'Jacob Johnson',
      last_updated_date: '2023-08-31T18:32:14Z',
      last_updated_for_name: null,
      name: 'Apex Capital Corp',
      notes: null,
      phone: null,
      phoneCountryCode: null,
      phone_country_info: {
        country_code: null,
        country_name: null,
        dial_code: null,
        display: null,
        friendly_name: null,
        hash: null,
        tmsCarrierId: null,
      },
      phone_ext: null,
      postal_code: '76161',
      state_province: 'TX',
      tin: null,
    },
    faxCountryCode: null,
    tmsCarrierId: 249087,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1332689',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'EEGALES INVESTMENTS ENTERPRISE L L C',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'WILTERLOVE@GMAIL.COM',
    contactFax: null,
    contactName: 'WILTER SIRIN',
    contactPhone: '202-655-8660',
    contactPhoneExt: null,
    dotNumber: '3877532',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 248286,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1421555',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'EH TRUCKING INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'EHTRUCKINGINC1@GMAIL.COM',
    contactFax: null,
    contactName: 'JASON PERILLA',
    contactPhone: '720-856-0060',
    contactPhoneExt: null,
    dotNumber: '4002328',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 250083,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1504588',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Unacceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'EMD TRUCKING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'EMDTRUCKINGLLC@GMAIL.COM',
    contactFax: null,
    contactName: 'MUHAMED ADEMOVIC',
    contactPhone: '314-728-4767',
    contactPhoneExt: null,
    dotNumber: '3396530',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249536,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1092548',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'ESES EXPRESS INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'USESESEXPRESS@GMAIL.COM',
    contactFax: null,
    contactName: 'EYDAR IBRAGIMOVICH GEYDAROV',
    contactPhone: '937-919-4050',
    contactPhoneExt: null,
    dotNumber: '2570940',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 250131,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC898403',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'EVOLUTION TRANSPORT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'EVOLUTIONTRANSPORTLLC1@GMAIL.COM',
    contactFax: null,
    contactName: 'MATTHEW WILSON',
    contactPhone: '360-485-3534',
    contactPhoneExt: null,
    dotNumber: '3537963',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249766,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1180193',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'FATE XPRESS INC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'FATETRUCKING@GMAIL.COM',
    contactFax: null,
    contactName: 'GURBINDER KAUR',
    contactPhone: '510-984-8404',
    contactPhoneExt: null,
    dotNumber: '3563155',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 251860,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1197472',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'FEC FREIGHT LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'FECTRUCKING1@YAHOO.COM',
    contactFax: null,
    contactName: 'ALI HAYNES',
    contactPhone: '330-203-7444',
    contactPhoneExt: null,
    dotNumber: '3807075',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249057,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1372457',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Moderate',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'FedEx Freight Economy',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: '',
    contactFax: null,
    contactName: 'Robert, Aaron, and Jerry. See notes...',
    contactPhone: '877-339-2774,,2,,3',
    contactPhoneExt: null,
    dotNumber: '86876',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 16,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-66562',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl', 'vltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['vltl', 'ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'fxnl',
    shipmentTerms: ['third_party'],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'Forward Air',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'aguzman@forwardair.com',
    contactFax: null,
    contactName: null,
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '2215557',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 116439,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-249708',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'fwdn',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'FRED P TRUCKING LLC',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'FREDPTRUCKINGLLC@GMAIL.COM',
    contactFax: null,
    contactName: 'FRED PHINISEE JR.',
    contactPhone: '317-457-9860',
    contactPhoneExt: null,
    dotNumber: '4036623',
    factoringCompany: null,
    faxCountryCode: null,
    tmsCarrierId: 249619,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: false,
    isReeferLtlQuotable: false,
    isRmisCertified: null,
    isTenderingEnabled: false,
    isTest: false,
    isTlQuotable: false,
    isVltlQuotable: false,
    mcNumber: 'MC1526461',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['tl'],
    phoneCountryCode: null,
    quotableLoadTypes: [],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: 'OK',
    saferwatchEnabled: true,
    saferwatchRiskAssessment: 'Acceptable',
    scac: '',
    shipmentTerms: [],
    tenderEmail: null,
  },
  {
    billingEmail: null,
    name: 'Frontline Freight',

    isBolBarcodeHidden: null,
    isDirectOnly: null,
    isDockHoursOnBol: null,
    isPickupNumOnBol: null,
    isQuoteNumOnBol: null,

    contactEmail: 'kavery@carrierlogistics.com',
    contactFax: null,
    contactName: 'Support',
    contactPhone: null,
    contactPhoneExt: null,
    dotNumber: '2215162',
    factoringCompany: null,
    faxCountryCode: 'US',
    tmsCarrierId: 8429,
    isActive: true,
    isBlacklisted: false,
    isDimsRequired: null,
    isHidden: false,
    isLtlQuotable: true,
    isReeferLtlQuotable: true,
    isRmisCertified: null,
    isTenderingEnabled: true,
    isTest: false,
    isTlQuotable: true,
    isVltlQuotable: true,
    mcNumber: 'MC-240311',
    mcpAssureAdvantageEnabled: false,
    mcpRiskAssessment: null,
    modes: ['ltl'],
    phoneCountryCode: 'US',
    quotableLoadTypes: ['ltl'],
    quoteEmail: null,
    rmisEnabled: false,
    rmisNonCertifiedReasons: null,
    saferwatchCertStatus: null,
    saferwatchEnabled: true,
    saferwatchRiskAssessment: null,
    scac: 'fcsy',
    shipmentTerms: [],
    tenderEmail: null,
  },
];
